config/routes.rb
Rails.application.routes.draw do
  resources :users
	root to: "users#index"
  resources :users, only: [:new, :create, :index]
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#logout'
  get 'welcome', to: 'sessions#welcome'
  get 'authorized', to: 'sessions#page_requires_login'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    enum role: [:staff, :manager, :admin]
    scope :filer_by_role, ->(role) { where("role <= ?", self.roles[role]) }

    def full_name
    	"#{self.first_name} #{self.last_name}"
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :unauthorized
  #helper_method :logged_in?
  helper_method :current_user, :is_staff?


  def current_user   
    User.find_by(id: session[:user_id])
  end

  def is_staff?
    (current_user.role == 'staff')
  end

  def unauthorized
    redirect_to '/login' unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :unauthorized, only: [:new, :create, :welcome]
  
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
        session[:user_id] = user.id 
        redirect_to (is_staff?(user) ? user : root_url)
    end
  end

  def welcome
    
  end

  def logout
     current_user = session[:user_id] = nil
     redirect_to root_url  
  end

  def page_requires_login
  end

  private

  def is_staff?(user)
    (user.role == 'staff')
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :unauthorized, only: [:new, :create]
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.filer_by_role(current_user.role)
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :first_name, :last_name, :password, :age, :address, :role)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UserDetails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <link href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <button class="ui inverted button">Standard</button>
    <%= link_to ('<i class="fa fa-sign-out"></i>').html_safe, logout_path,style: "margin-left: 80%;", class: "btn btn-danger" unless current_user.blank? %>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="login_cont">
<div class="form-group">
        <label for="name"><%= form.label :User_name%></label>
    <%= form.text_field :username, class: "form-control", placeholder: "Enter UserName" %>
  </div>

  <div class="form-group">
        <label for="name"><%= form.label :first_name %></label>
    <%= form.text_field :first_name, class: "form-control", placeholder: "Enter FirstName" %>
  </div>

    <div class="form-group">
        <label for="name"><%= form.label :last_name %></label>
    <%= form.text_field :last_name, class: "form-control", placeholder: "Enter LastName" %>
  </div>
    <div class="form-group">
        <label for="password"><%= form.label :password %></label>
    <%= form.password_field :password, class: "form-control", placeholder: "Enter Password" %>
  </div>

    <div class="form-group">
        <label for="number"><%= form.label :age %></label>
    <%= form.number_field :age, class: "form-control", placeholder: "Enter Age" %>
  </div>

    <div class="form-group">
        <label for="name"><%= form.label :address %></label>
    <%= form.text_area :address, class: "form-control", placeholder: "Enter Address" %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1 style="text-align: center;">Editing User</h1>

<%= render 'form', user: @user %>

<div class="row", style="margin-left: 50%;">
  <div class="col-sm-2"><%= link_to 'Show', @user %> </div>
  <div class="col-sm-2"><%= link_to 'Back', users_path %></div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<!--%= button_to "New User",class: "btn btn-success", new_user_path%-->
<%= link_to 'New User', new_user_path %>
<div class="container">

<h1 style="text-align: center;">User Details</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Username</th>
      <th>Full name</th>
      <th>Age</th>
      <th>Address</th>
      <th>Role</th>
      <th>Show</th>
      <th>Edit</th>
      <th>Delete</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.full_name %></td>
        <td><%= user.age %></td>
        <td><%= user.address %></td>
        <td><%= user.role %></td>
        <td><%= link_to ('<i class="fa fa-eye"></i>').html_safe, user , class: "btn btn-info"%></td>
        <td><%= link_to ('<i class="fa fa-edit"></i>').html_safe, edit_user_path(user), class: "btn btn-success" %></td>
        <td><%= link_to ('<i class="fa fa-trash"></i>').html_safe, user, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>
<br>

app/views/users/new.html.erb
<h1 style="text-align: center;">New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>


<div class="container">

<h2 style="text-align: center;">User Profile</h2>

<table class="table table-striped">
  <tbody>
    <tr>
      <td>Username:</td>
      <td><%= @user.username %></td>
    </tr>
    <tr>
      <td>Full name:</td>
      <td><%= @user.full_name %></td>
    </tr>
<tr>
<td>Age:</td>
  <td><%= @user.age %></td>
</tr>
<tr>
<td>Address:</td>
  <td><%= @user.address %></td>
</tr>
<tr>
<td>Role:</td>
  <td><%= @user.role %></td>
</tr>
<tr>
<td><%= link_to 'Edit', edit_user_path(@user) %></td>
<td><%= link_to 'Back', users_path %></td>
</tr>
 </tbody>
  </table>
</div>